name: nawel
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  carousel_slider: ^5.1.1
  shared_preferences: ^2.5.3
  go_router: ^15.2.0
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  flutter_bloc: ^9.1.1
  cloud_firestore: ^5.6.9
  equatable: ^2.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6



flutter_native_splash:
  color: "#ffffff" # Background color of the splash presentation
  image: assets/splash.png # Path to the splash presentation image
  android_12:
   image: assets/frame2.png

flutter:
  uses-material-design: true
  assets:
     - assets/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
